services:
  wg-easy:
    environment:
     - LANG=en
     - WG_HOST=wg.$DOMAIN
    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wg-easy
    volumes:
      - /root/wireguard:/etc/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - proxy-network
      - traefik
    ports:
       - "51820:51820/udp"
       - "51821:51821/tcp"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.routers.wg-easy.rule=Host(`wg.$DOMAIN`)"
      - "traefik.http.routers.wg-easy.entrypoints=websecure"
      - "traefik.http.routers.wg-easy.service=wg-easy"
      - "traefik.http.services.wg-easy.loadbalancer.server.port=51821"

networks:
  traefik:
    name: traefik_public # traefik public network
    external: true
  proxy-network:
    external: true